#:schema https://mise.jdx.dev/schema/mise.json

[hooks]
enter = [
  { shell = "bash", script = "command -v hum >/dev/null && source <(hum completion bash)" },
  { shell = "zsh", script = "command -v hum >/dev/null && source <(hum completion zsh)" },
  { shell = "fish", script = "type -q hum; and hum completion fish | source" },
]

[tools]
bun = "1.4.2"
prettier = "3.9.6"
gitleaks = "8.30.1"
lefthook = "2.1.12"
task = "3.53.1"
"github:brettinternet/hum" = "0.12.1"

[settings]
disable_backends = ["asdf"]
npm.bun = true
